# Generated by Django 5.2.4 on 2025-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSemMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('t1_marks', models.FloatField()),
                ('t2_marks', models.FloatField()),
                ('t3_marks', models.FloatField()),
                ('current_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('code_question', models.CharField(max_length=5600)),
                ('test_output_1', models.CharField(max_length=2500)),
                ('test_output_2', models.CharField(max_length=5555)),
                ('mcq_ques', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_no', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('code_marks', models.IntegerField()),
                ('mcq_marks', models.IntegerField()),
                ('test_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=250)),
                ('fac_mail', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PastMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_no', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_no', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=100)),
                ('parents_contact', models.BigIntegerField()),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=250)),
                ('sem', models.IntegerField()),
            ],
        ),
    ]
