# Generated by Django 5.2.4 on 2025-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='test_output_2',
            field=models.JSONField(),
        ),
    ]
