# Generated by Django 5.2.4 on 2025-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exampaper_test_output_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_no', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('total_lectures', models.IntegerField()),
                ('total_attended', models.IntegerField()),
            ],
        ),
    ]
