# Generated by Django 5.2.4 on 2025-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_name',
            field=models.CharField(default='General', max_length=250),
            preserve_default=False,
        ),
    ]
