# Generated by Django 5.2.4 on 2025-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendance_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
