# Generated by Django 5.2.4 on 2025-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_faculty_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attd_date',
            field=models.DateField(auto_now=True),
        ),
    ]
