# Generated by Django 5.2.4 on 2025-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attendance_attd_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploader_id', models.IntegerField()),
                ('uploader_name', models.CharField(max_length=250)),
                ('subject_name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('doc', models.BinaryField()),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
