# Generated by Django 5.2.4 on 2025-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
