<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-13 05:16

import django.db.models.deletion
=======
# Generated by Django 5.2.4 on 2025-08-12 19:27

>>>>>>> e7484d99a037ed8b12dd97f001676e7a00474739
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notes_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='sem',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='sem', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='api.subjectdetails'),
=======
            field=models.IntegerField(default=7),
            preserve_default=False,
>>>>>>> e7484d99a037ed8b12dd97f001676e7a00474739
        ),
    ]
