<<<<<<< HEAD

import django.db.models.deletion

=======
>>>>>>> 28d5452ac3ff740e96aeb774d9b843b7b5a34ce0
# Generated by Django 5.2.4 on 2025-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notes_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='sem',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
