# Generated by Django 5.2.4 on 2025-08-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notes_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='sem',
            field=models.ForeignKey(db_column='sem', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='api.subjectdetails'),
        ),
    ]
