# Generated by Django 5.2.4 on 2025-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exampaper_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
