# Generated by Django 5.2.4 on 2025-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_exampaper_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='code_question',
            field=models.CharField(blank=True, max_length=5600, null=True),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='test_output_1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='test_output_2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
